// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xinprjcoxfufhyckvghj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpbnByamNveGZ1Zmh5Y2t2Z2hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NDgzNjksImV4cCI6MjA2MzIyNDM2OX0.ISG4fO9-fHxj3NrBlY4l7eZKg8an16aqGNjZF0gSeRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);